[buildPlans.viosevka]
family   = "Viosevka"
spacing  = "normal"
serifs   = "slab"
no-cv-ss = true

[buildPlans.viosevka.variants.design]
capital-g = "toothless-corner-inward-serifed-capped"
capital-j = "serifed-both-sides"
capital-k = "curly"
capital-q = "crossing"
capital-r = "curly"
a = "single-storey-motion-serifed"
g = "double-storey"
k = "curly"
lower-iota = "zshaped"
lower-lambda = "curly-turn"
cyrl-ka = "curly"
three = "flattop"
six = "closed-contour"
seven = "bend-serifed"
eight = "two-circles"
nine = "closed-contour"
asterisk = "hex-low"
underscore = "above-baseline"
paragraph-sign = "low"
paren = "flat-arc"
brace = "straight"
ampersand = "upper-open"
at = "short"
dollar = "open"
cent = "open"
percent = "rings-continuous-slash"
lig-ltgteq = "slanted"
question = "corner"

  [buildPlans.viosevka.ligations]
  inherits = "dlig"
