[buildPlans.Viosevka]
family = "Viosevka"
spacing = "normal"
serifs = "slab"
noCvSs = true
exportGlyphNames = false

[buildPlans.Viosevka.variants.design]
capital-g = "toothless-corner-inward-serifed-capped"
capital-j = "serifed-both-sides"
capital-q = "crossing-baseline"
g = "double-storey"
lower-iota = "zshaped"
lower-lambda = "curly-turn"
three = "flat-top"
six = "closed-contour"
seven = "bend-serifed"
eight = "two-circles"
nine = "closed-contour"
asterisk = "hex-low"
underscore = "above-baseline"
paren = "flat-arc"
brace = "straight"
ampersand = "upper-open"
at = "compact"
dollar = "open"
cent = "open"
percent = "rings-continuous-slash"
question = "corner"
pilcrow = "low"
lig-ltgteq = "slanted"

  [buildPlans.Viosevka.ligations]
  inherits = "dlig"
