name: Build font

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version: '20'

            - name: Get system packages
              run: sudo apt install ttfautohint libttfautohint-dev

            - name: Run build script
              run: sh build.sh

            - uses: actions/upload-artifact@v4
              with:
                  name: viosevka-ttf
                  path: src/dist/viosevka/ttf

            - uses: actions/upload-artifact@v4
              with:
                  name: viosevka-ttf-unhinted
                  path: src/dist/viosevka/ttf-unhinted
