name: Build font

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-node@v2
              with:
                  node-version: '14'

            - name: Get system packages
              run: sudo apt install ttfautohint libttfautohint-dev

            - name: Run build script
              run: sh build.sh

            - uses: actions/upload-artifact@v2
              with:
                  name: Viosevka
                  path: Iosevka-6.0.0-preview.1/dist/viosevka
